// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nclavsvzjzegqvkjezyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jbGF2c3Z6anplZ3F2a2plenl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDg0NDgsImV4cCI6MjA2NTUyNDQ0OH0.jsvrU_98tsdHnPqEtIxg_MzB7d3MoZBa6FvWmwfuJA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);